package com.felix.miraagent.trace;

public enum TraceEventType {
    RUN_STARTED,
    PROMPT_BUILT,
    MODEL_REQUESTED,
    MODEL_RESPONDED,
    TOOL_CALL_PARSED,
    TOOL_CALL_REPAIRED,
    TOOL_CALL_RECEIVED,
    TOOL_EXECUTION_STARTED,
    TOOL_EXECUTION_FINISHED,
    TOOL_EXECUTION_FAILED,
    TOOL_RESULT_PERSISTED,
    PERMISSION_DENIED,
    CONTEXT_COMPRESSED,
    SESSION_PERSISTED,
    BACKGROUND_REVIEW_STARTED,
    BACKGROUND_REVIEW_FINISHED,
    SKILL_UPDATED,
    MEMORY_UPDATED,
    FINAL_RESPONSE,
    RUN_FAILED
}
